LANGS = {
    "zh": {
        "window_title": "miHoYo Tool Pro",
        "title": "miHoYo Tool",
        "labels": {
            "base_delay": "基础延迟 (ms)",
            "random_delay": "随机浮动 (ms)",
            "start_hotkey": "开始热键",
            "stop_hotkey": "停止热键",
        },
        "buttons": {
            "start": "开始",
            "stop": "停止",
            "recording": "请按键...",
            "none": "无",
            "invalid_key": "无效键",
            "theme_toggle": "切换主题",
            "lang_toggle": "中/EN",
            "pin": "置顶",
            "unpin": "取消置顶",
            "settings": "设置",
        },
        "status": {
            "waiting": "等待中",
            "ready": "准备开始",
            "injecting": "准备中...",
            "typing": "输入中",
            "stopping": "停止中",
            "stopped": "已停止",
            "interrupted": "已中断",
            "success": "成功",
            "done": "完成",
            "empty_clipboard": "剪贴板为空",
            "invalid_params": "参数错误",
            "stopped_by_user": "已停止",
            "preparing": "准备中",
        },
        "window_buttons": {"minimize": "一", "close": "×"},
        "messages": {
            "hotkey_conflict_title": "热键冲突",
            "hotkey_conflict_body": "按键 '{key}' 已被占用",
            "invalid_number_hint": "请输入数字，例如 10 / 5",
            "settings_title": "设置",
            "base_label": "基础延迟 (ms)",
            "random_label": "随机浮动 (ms)",
            "start_hotkey": "开始热键",
            "stop_hotkey": "停止热键",
            "hotkey_conflict": "热键注册失败，请更换按键",
            "apply_failed": "应用失败",
            "hotkey_hint": "开始: {start} / 停止: {stop}",
        },
    },
    "en": {
        "window_title": "miHoYo Tool Pro",
        "title": "miHoYo Tool",
        "labels": {
            "base_delay": "Base delay (ms)",
            "random_delay": "Random jitter (ms)",
            "start_hotkey": "Start hotkey",
            "stop_hotkey": "Stop hotkey",
        },
        "buttons": {
            "start": "Start",
            "stop": "Stop",
            "recording": "Press a key...",
            "none": "None",
            "invalid_key": "Invalid",
            "theme_toggle": "Theme",
            "lang_toggle": "EN/中",
            "pin": "Pin",
            "unpin": "Unpin",
            "settings": "Settings",
        },
        "status": {
            "waiting": "Waiting...",
            "ready": "Ready to start",
            "injecting": "Injecting...",
            "typing": "Typing...",
            "stopping": "Stopping...",
            "stopped": "Stopped",
            "interrupted": "Interrupted",
            "success": "Success",
            "done": "Done",
            "empty_clipboard": "Clipboard is empty",
            "invalid_params": "Invalid parameters",
            "stopped_by_user": "Stopped by user",
            "preparing": "Preparing...",
        },
        "window_buttons": {"minimize": "-", "close": "×"},
        "messages": {
            "hotkey_conflict_title": "Hotkey conflict",
            "hotkey_conflict_body": "Key '{key}' is already taken",
            "invalid_number_hint": "Please enter numbers, e.g. 10 / 5",
            "settings_title": "Settings",
            "base_label": "Base delay (ms)",
            "random_label": "Random jitter (ms)",
            "start_hotkey": "Start hotkey",
            "stop_hotkey": "Stop hotkey",
            "hotkey_conflict": "Failed to register hotkey, try another key",
            "apply_failed": "Apply failed",
            "hotkey_hint": "Start: {start} / Stop: {stop}",
        },
    },
}


def get_text(lang: str, group: str, key: str, **kwargs) -> str:
    data = LANGS.get(lang, LANGS["zh"])
    value = data[group][key]
    return value.format(**kwargs)
