LANGS = {
    "zh": {
        "window_title": "miHoYo Tool Pro",
        "title": "miHoYo Tool",
        "labels": {
            "base_delay": "基础延迟 (ms)",
            "random_delay": "随机浮动 (ms)",
            "start_hotkey": "开始热键",
            "stop_hotkey": "停止热键",
        },
        "buttons": {
            "start": "开始",
            "stop": "停止",
            "recording": "请按键...",
            "none": "无",
            "invalid_key": "无效键",
            "theme_toggle": "切换主题",
            "lang_toggle": "中/EN",
            "pin": "置顶",
            "unpin": "取消置顶",
            "settings": "设置",
        },
        "status": {
            "waiting": "等待中",
            "ready": "准备开始",
            "injecting": "准备中...",
            "typing": "输入中",
            "stopping": "停止中",
            "stopped": "已停止",
            "interrupted": "已中断",
            "success": "成功",
            "done": "完成",
            "continuing": "继续中...",
            "resume_ready": "可继续之前的任务",
            "no_pending": "没有可继续的内容",
            "empty_clipboard": "剪贴板为空",
            "invalid_params": "参数错误",
            "stopped_by_user": "已停止",
            "preparing": "准备中",
        },
        "window_buttons": {"minimize": "一", "close": "×"},
        "messages": {
            "hotkey_conflict_title": "热键冲突",
            "hotkey_conflict_body": "按键 '{key}' 已被占用",
            "invalid_number_hint": "请输入数字，例如 10 / 5",
            "settings_title": "设置",
            "base_label": "基础延迟 (ms)",
            "random_label": "随机浮动 (ms)",
            "countdown_label": "启动倒计时 (s)",
            "start_hotkey": "开始热键",
            "continue_hotkey": "暂停/继续热键",
            "hotkey_conflict": "热键注册失败，请更换按键",
            "hotkey_conflict_runtime": "热键 {key} 已占用，已恢复为上一个可用设置",
            "apply_failed": "应用失败",
            "hotkey_hint": "开始: {start} / 暂停: {continue}",
            "hotkey_invalid": "请输入有效的快捷键",
            "hotkey_override": "已清除相同快捷键，当前设置为 {key}",
            "hotkey_saved": "快捷键 {key} 已保存",
        },
    },
    "en": {
        "window_title": "miHoYo Tool Pro",
        "title": "miHoYo Tool",
        "labels": {
            "base_delay": "Base delay (ms)",
            "random_delay": "Random jitter (ms)",
            "start_hotkey": "Start hotkey",
            "stop_hotkey": "Stop hotkey",
        },
        "buttons": {
            "start": "Start",
            "stop": "Stop",
            "recording": "Press a key...",
            "none": "None",
            "invalid_key": "Invalid",
            "theme_toggle": "Theme",
            "lang_toggle": "EN/中",
            "pin": "Pin",
            "unpin": "Unpin",
            "settings": "Settings",
        },
        "status": {
            "waiting": "Waiting...",
            "ready": "Ready to start",
            "injecting": "Injecting...",
            "typing": "Typing...",
            "stopping": "Stopping...",
            "stopped": "Stopped",
            "interrupted": "Interrupted",
            "success": "Success",
            "done": "Done",
            "continuing": "Resuming...",
            "resume_ready": "Ready to resume previous task",
            "no_pending": "Nothing to resume",
            "empty_clipboard": "Clipboard is empty",
            "invalid_params": "Invalid parameters",
            "stopped_by_user": "Stopped by user",
            "preparing": "Preparing...",
        },
        "window_buttons": {"minimize": "-", "close": "×"},
        "messages": {
            "hotkey_conflict_title": "Hotkey conflict",
            "hotkey_conflict_body": "Key '{key}' is already taken",
            "invalid_number_hint": "Please enter numbers, e.g. 10 / 5",
            "settings_title": "Settings",
            "base_label": "Base delay (ms)",
            "random_label": "Random jitter (ms)",
            "countdown_label": "Countdown (s)",
            "start_hotkey": "Start hotkey",
            "continue_hotkey": "Pause/Resume hotkey",
            "hotkey_conflict": "Failed to register hotkey, try another key",
            "hotkey_conflict_runtime": "Hotkey {key} is taken, restored previous working binding",
            "apply_failed": "Apply failed",
            "hotkey_hint": "Start: {start} / Pause: {continue}",
            "hotkey_invalid": "Please press a valid hotkey",
            "hotkey_override": "Cleared duplicate and set to {key}",
            "hotkey_saved": "Hotkey {key} saved",
        },
    },
}


def get_text(lang: str, group: str, key: str, **kwargs) -> str:
    data = LANGS.get(lang, LANGS["zh"])
    value = data[group][key]
    return value.format(**kwargs)
